# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePswForm.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChangePswForm(object):
    def setupUi(self, ChangePswForm):
        ChangePswForm.setObjectName("ChangePswForm")
        ChangePswForm.resize(469, 399)
        ChangePswForm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.turn2visible1_3 = QtWidgets.QPushButton(ChangePswForm)
        self.turn2visible1_3.setGeometry(QtCore.QRect(410, 270, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.turn2visible1_3.setFont(font)
        self.turn2visible1_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.turn2visible1_3.setAutoFillBackground(False)
        self.turn2visible1_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/wtc_py/pic/02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turn2visible1_3.setIcon(icon)
        self.turn2visible1_3.setIconSize(QtCore.QSize(40, 40))
        self.turn2visible1_3.setFlat(True)
        self.turn2visible1_3.setObjectName("turn2visible1_3")
        self.pushButton_9 = QtWidgets.QPushButton(ChangePswForm)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 330, 251, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_35 = QtWidgets.QPushButton(ChangePswForm)
        self.pushButton_35.setGeometry(QtCore.QRect(300, 90, 51, 31))
        self.pushButton_35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_35.setAutoFillBackground(False)
        self.pushButton_35.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/open2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_35.setIcon(icon1)
        self.pushButton_35.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_35.setFlat(True)
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_15 = QtWidgets.QLabel(ChangePswForm)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 331, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_15.setObjectName("label_15")
        self.closeenterpsw = QtWidgets.QPushButton(ChangePswForm)
        self.closeenterpsw.setGeometry(QtCore.QRect(430, 0, 41, 31))
        self.closeenterpsw.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/wtc_py/pic/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeenterpsw.setIcon(icon2)
        self.closeenterpsw.setFlat(True)
        self.closeenterpsw.setObjectName("closeenterpsw")
        self.label_72 = QtWidgets.QLabel(ChangePswForm)
        self.label_72.setGeometry(QtCore.QRect(20, 90, 271, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(89, 89, 89);")
        self.label_72.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.line_33 = QtWidgets.QFrame(ChangePswForm)
        self.line_33.setGeometry(QtCore.QRect(20, 240, 431, 10))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.lineEdit_7 = QtWidgets.QLineEdit(ChangePswForm)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 270, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setToolTip("")
        self.lineEdit_7.setStatusTip("")
        self.lineEdit_7.setWhatsThis("")
        self.lineEdit_7.setAccessibleName("")
        self.lineEdit_7.setAccessibleDescription("")
        self.lineEdit_7.setStyleSheet("\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character:42;\n"
"}\n"
"")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.line_34 = QtWidgets.QFrame(ChangePswForm)
        self.line_34.setGeometry(QtCore.QRect(20, 300, 431, 10))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.lineEdit_6 = QtWidgets.QLineEdit(ChangePswForm)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 210, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setToolTip("")
        self.lineEdit_6.setStatusTip("")
        self.lineEdit_6.setWhatsThis("")
        self.lineEdit_6.setAccessibleName("")
        self.lineEdit_6.setAccessibleDescription("")
        self.lineEdit_6.setStyleSheet("\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character:42;\n"
"}\n"
"")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.turn2visible1_2 = QtWidgets.QPushButton(ChangePswForm)
        self.turn2visible1_2.setGeometry(QtCore.QRect(410, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.turn2visible1_2.setFont(font)
        self.turn2visible1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.turn2visible1_2.setAutoFillBackground(False)
        self.turn2visible1_2.setText("")
        self.turn2visible1_2.setIcon(icon)
        self.turn2visible1_2.setIconSize(QtCore.QSize(40, 40))
        self.turn2visible1_2.setFlat(True)
        self.turn2visible1_2.setObjectName("turn2visible1_2")
        self.line_35 = QtWidgets.QFrame(ChangePswForm)
        self.line_35.setGeometry(QtCore.QRect(20, 180, 431, 10))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.lineEdit_8 = QtWidgets.QLineEdit(ChangePswForm)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 150, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setToolTip("")
        self.lineEdit_8.setStatusTip("")
        self.lineEdit_8.setWhatsThis("")
        self.lineEdit_8.setAccessibleName("")
        self.lineEdit_8.setAccessibleDescription("")
        self.lineEdit_8.setStyleSheet("\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character:42;\n"
"}\n"
"")
        self.lineEdit_8.setFrame(False)
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.turn2visible1_4 = QtWidgets.QPushButton(ChangePswForm)
        self.turn2visible1_4.setGeometry(QtCore.QRect(410, 150, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.turn2visible1_4.setFont(font)
        self.turn2visible1_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.turn2visible1_4.setAutoFillBackground(False)
        self.turn2visible1_4.setText("")
        self.turn2visible1_4.setIcon(icon)
        self.turn2visible1_4.setIconSize(QtCore.QSize(40, 40))
        self.turn2visible1_4.setFlat(True)
        self.turn2visible1_4.setObjectName("turn2visible1_4")

        self.retranslateUi(ChangePswForm)
        QtCore.QMetaObject.connectSlotsByName(ChangePswForm)

    def retranslateUi(self, ChangePswForm):
        _translate = QtCore.QCoreApplication.translate
        ChangePswForm.setWindowTitle(_translate("ChangePswForm", "Form"))
        self.pushButton_9.setText(_translate("ChangePswForm", "Confirm"))
        self.label_15.setText(_translate("ChangePswForm", "Set Login Password"))
        self.label_72.setText(_translate("ChangePswForm", "Enter password when Login:"))
        self.lineEdit_7.setPlaceholderText(_translate("ChangePswForm", "Enter your password again"))
        self.lineEdit_6.setPlaceholderText(_translate("ChangePswForm", "Enter your password "))
        self.lineEdit_8.setPlaceholderText(_translate("ChangePswForm", "Enter your old password "))

